<?php
/*
* Care by Zinc in Product Page
*/

?>
<?php  	$product_id = Mage::registry('current_product')->getId();
	$product = Mage::getModel('catalog/product')->load($product_id); 
	$productType = $product->getTypeId();
	$price = $product->getFinalPrice();
	$helper =  Mage::helper('carebyzinc');
        if(($productType == Mage_Catalog_Model_Product_Type::TYPE_SIMPLE || $productType == Mage_Catalog_Model_Product_Type::TYPE_CONFIGURABLE) && ($product->getCarebyzinc() == 1) &&  ($helper->validatePrice($price) == 'true') && ($helper->checkQuoteVisibility())):
             
	      $zip = $helper->getZipCode(); ?>
<div class="product-box">
<h1 class="product-title"><?php echo $helper->getTitle()?></h1>
<input type="text" name="zipcode" id="zipcode" value="<?php echo $zip ;?>" placeholder="Enter Zip code here" style="width:21%"/>
<button class="btn-zinc showCarebyzinc" onclick="showCarebyzinc(); return false;">Get Quote <span id="care-loader" class="care-loader"></span></button>  
<div id="carebyzincCnt" class="product-wrap"></div>
</div>
<script>
//<![CDATA[
function showCarebyzinc(){
	var val = document.getElementsByClassName("super-attribute-select");
	var customoption = document.getElementsByClassName("product-custom-option");
	var i;	
	var configOptions = '';
	if(val.length)
		configOptions = '{';
	for (i = 0; i < val.length; i++) {
		var option = (val[i].name).match(/\d+/)[0];
	 	configOptions = configOptions+'"'+option+'":'+val[i].value;	
	 	if(i != (val.length-1))
	 		configOptions = configOptions+',';   
	}
	if(val.length)
		configOptions = configOptions+'}';
	var customoptionPrice = 0;	
	for (i = 0; i < customoption.length; i++) {
		var option = customoption[i].value;
		var selectedIndex = customoption[i].selectedIndex;
		if(selectedIndex)
			customoptionPrice = customoptionPrice + customoption[i][selectedIndex].getAttribute('price');
	}
	var zip = document.getElementById('zipcode').value;
	if(zip){	
		
		if(/(^[A-z0-9]{2,10}([\s]{0,1}|[\-]{0,1})[A-z0-9]{2,10}$)/.test(zip)){
			  var url = '<?php echo $this->getUrl("carebyzinc/index/pricequote") ?>';
			  jQuery( "button" ).addClass( "selected" );
			  jQuery("#care-loader").addClass('show');
			  new Ajax.Request(url, {
			  method: 'post',
			  parameters: {pid: <?php echo Mage::registry('current_product')->getId(); ?>,zip:zip,configOptions:configOptions,customoptionPrice:customoptionPrice},
			  onComplete: function(transport) {
					  var content = JSON.parse(transport.responseText); 
					  jQuery("#carebyzincCnt").show();	
					  $('carebyzincCnt').update(content);	
					  jQuery("#care-loader").removeClass('show');	
					   jQuery( "button" ).removeClass( "selected" );
					// jQuery(".showCarebyzinc").hide();
					//  jQuery("#zipcode").hide();		  
				}
				  
			});
		}
		else
			alert('Enter a valid zipcode');
	}else
		alert('Enter a valid zipcode');
}
	jQuery(".configurable-swatch-list li a").click(function(){
		  jQuery("#carebyzincCnt").hide();
		  $('carebyzincCnt').update('');	
	});
	jQuery("select.super-attribute-select").change(function(){
		  jQuery("#carebyzincCnt").hide();
		  $('carebyzincCnt').update('');	
	});
	
	

	
//]]>	 
</script>
<?php endif; ?>
