<?php $quoteData = $this->getQuoteData(); 
	$itemId = $this->getItemId();
?>
<?php if(! empty($quoteData)): ?>

<?php if( is_array($quoteData)): ?>
<ul class="product-list">
  <?php foreach($quoteData as $item): ?>
      <li>
          <div class="bx-l">
              <div class="squared input">
                  <input type="radio" value="<?php echo $item['id']; ?>" id="carebyzinc_<?php echo $itemId.'_'.$item['id']; ?>" name="carebyzinc_option_<?php echo $itemId?>" />
                  <label for="carebyzinc_<?php echo $itemId.'_'.$item['id']; ?>"></label>
              </div>
          </div>
          <div class="bx-r">
              <h2 class="p-price"><?php echo Mage::helper('core')->currency($item['price_per_year']); ?></h2>
              <h3 class="p-name quotelabel"><?php echo $item['description']; ?></h3>
          </div>
      </li>
  <?php endforeach; ?>
</ul>
		<button type="button" title="Add" class="button" id="button-container_<?php echo $itemId?>" onclick="updateCareByZinc(<?php echo $itemId?>)"><span><span>Add</span></span></button>
<?php else:
echo $quoteData;
?>
<?php endif; ?>
<?php else:
echo 'No quotes available';
?>
<?php endif; ?>
