<?php $quoteData = $this->getQuoteData();?>
<?php if(! empty($quoteData)): ?>
<?php if( is_array($quoteData)): ?>
<div class="product-wrap">

<ul class="product-list">
  <?php foreach($quoteData as $item): ?>
      <li>
          <div class="bx-l">
              <div class="squared input">
                  <input type="radio" value="<?php echo $item['id']; ?>" id="carebyzinc_<?php echo $item['id']; ?>" name="carebyzinc_option" onclick="checkAction(this)"/>
                  <label for="carebyzinc_<?php echo $item['id']; ?>"></label>
              </div>
          </div>
          <div class="bx-r">
              <h2 class="p-price"><?php echo Mage::helper('core')->currency($item['price_per_year']); ?></h2>
              <h3 class="p-name quotelabel"><?php echo $item['description']; ?></h3>
          </div>
      </li>
  <?php endforeach; ?>
</ul>
</div>
<script>
//<![CDATA[
 jQuery(".quotelabel").on("click","a", function(event){
        event.preventDefault();
        var elementURL = jQuery(this).attr("href");
        jQuery.colorbox({iframe: true, href: elementURL, innerWidth: 645,fastIframe: false, innerHeight: 509,width:"70%"});
      });
  //]]> 
</script>
<?php else:?>
<div id="warning_div"><?php echo $quoteData;?></div>
<script>
//<![CDATA[
hideDivData();
function hideDivData(){
  setTimeout(function() {
    jQuery('#warning_div').fadeOut('fast');
  }, 1000); 
}
//]]>   
</script>
<?php endif; ?>
<?php else:?>
<p style="color:red;"><?php echo $this->__( 'No quotes available');?>
</p>
<?php endif; ?>
